#!/bin/sh
set -e

NAME=emby-server
CONF_FILE=/etc/${NAME}.conf
DEFAULT_FILE=/etc/default/${NAME}

# Source Emby server default configuration
if [ -f $DEFAULT_FILE ]; then
  . $DEFAULT_FILE
fi

# Source Emby server user configuration overrides
if [ -f $CONF_FILE ]; then
  . $CONF_FILE
fi

# Data directory where Emby database, cache and logs are stored
PROGRAMDATA=${EMBY_DATA-/var/lib/$NAME}

case "$1" in
  purge)
    echo PURGE | debconf-communicate $NAME
    if [ -f /etc/init.d/$NAME ]; then
      update-rc.d -f $NAME remove > /dev/null || exit $?
    fi

    if [ -d $PROGRAMDATA ]; then
      rm -rf $PROGRAMDATA
    fi
    userdel emby > /dev/null || true
    delgroup --quiet emby || true
    [ -f /etc/init.d/emby ] && rm /etc/init.d/emby
    [ -f /etc/init.d/emby-server ] && rm /etc/init.d/emby-server
    [ -f /etc/init.d/emby-server-beta ] && rm /etc/init.d/emby-server-beta
    [ -f /etc/init.d/emby-server-dev ] && rm /etc/init.d/emby-server-dev
    [ -f /etc/init.d/mediabrowser ] && rm /etc/init.d/mediabrowser
    [ -f /etc/init/emby-server ] && rm /etc/init/emby-server
    [ -f /etc/init/emby-server-beta ] && rm /etc/init/emby-server-beta
    [ -f /etc/init/emby-server-dev ] && rm /etc/init/emby-server-dev
    [ -f /etc/emby-server.conf ] && rm /etc/emby-server.conf
    [ -f /usr/bin/emby-server ] && rm /usr/bin/emby-server
    [ -f /etc/sudoers.d/emby ] && rm /etc/sudoers.d/emby
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
exit 0
