#!/bin/sh
set -e
set -u

NAME=emby-server
CONF_FILE=/etc/${NAME}.conf
DEFAULT_FILE=/etc/default/${NAME}

# Source Emby server default configuration
. $DEFAULT_FILE

# Source Emby server user configuration overrides
if [ -f $CONF_FILE ]; then
    . $CONF_FILE
else
    echo "${CONF_FILE} not found using default settings.";
fi

# Data directory where Emby database, cache and logs are stored
PROGRAMDATA=${EMBY_DATA-/var/lib/$NAME}


case "$1" in
    install|upgrade)
        . /usr/share/debconf/confmodule
        db_version 2.0
        db_capb backup
        
        PID_FILE=`find /var/run -name "emby*.pid" -print -quit`
        [ -n "$PID_FILE" ] && EMBY_PID=`cat ${PID_FILE} 2> /dev/null || true`
        if [ -n "$EMBY_PID" ]; then 
            echo "Stopping Emby Server!"
            # try graceful termination;
            # Figure out how to start/stop emby-server daemon
            if which service >/dev/null 2>&1; then
                _service_invoke="service ${NAME}"
            elif which invoke-rc.d >/dev/null 2>&1; then
                _service_invoke="invoke-rc.d ${NAME}"
            else
                _service_invoke=/etc/init.d/${NAME}
            fi
            ${_service_invoke} stop 2>/dev/null || true
            kill -USR1 $EMBY_PID > /dev/null 2>&1 || true
            sleep 1
            [ -f $PID_FILE ] && rm $PID_FILE
            if ps -p $EMBY_PID > /dev/null; then
                db_fset $NAME/old-running seen false || true
                db_input critical $NAME/old-running || true 
                db_go || true
                exit 1
            fi
        fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
exit 0
