#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

EDGE=${EDGE:-0}
STABLE=${STABLE:-1}

if [[ $EDGE -eq 1 ]]; then
  echo "Updating ${APP_NAME}..."
  if [[ $STABLE -eq 1 ]]; then
    RELEASE_VERSION=$(curl -sL https://github.com/mediaBrowser/Emby/releases.atom | grep -A 1 -e 'link.*alternate' | grep -e '    <' | sed 'N;s/\n/ /' | grep -v 'beta' | head -1 | sed 's%.*/tag/\([^"]*\).*%\1%')
  else
    RELEASE_VERSION=$(curl -sL https://github.com/mediaBrowser/Emby/releases.atom | grep -A 1 -e 'link.*alternate' | grep -e '    <' | sed 'N;s/\n/ /' | grep 'beta' | head -1 | sed 's%.*/tag/\([^"]*\).*%\1%')
  fi
  curl -o /var/tmp/emby.zip -L https://github.com/MediaBrowser/Emby/releases/download/${RELEASE_VERSION}/Emby.Mono.zip
  mkdir /usr/lib/emby-server/bin
  unzip /var/tmp/emby.zip -d /usr/lib/emby-server/bin
fi
