#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

APP_UID=${APP_UID:-1000}
APP_GID=${APP_GID:-1000}

APP_USER=${APP_USER:-appuser}

# del emby user and group
userdel -f emby 2> /dev/null
groupdel emby 2> /dev/null

if getent group ${APP_GID} > /dev/null; then
  groupdel ${APP_GID} 2> /dev/null
fi

# add USER GID
if ! getent group ${APP_USER} > /dev/null; then
  groupadd -f -g ${APP_GID} ${APP_USER} > /dev/null 2>&1
fi

if getent passwd ${APP_UID} > /dev/null; then
  userdel ${APP_UID} 2> /dev/null
fi

# create user with APP_UID
if ! getent passwd ${APP_USER} > /dev/null; then
  useradd --system \
    --shell /bin/false \
    --no-create-home \
    --uid ${APP_UID} \
    --gid ${APP_GID} \
    --comment 'Emby Server' ${APP_USER} > /dev/null 2>&1
fi

# ensure the group emby exist no matter what
if ! getent group emby  > /dev/null; then
  groupadd -f emby > /dev/null 2>&1
fi

CURR_UID=$(stat -c%u /config)
CURR_GID=$(stat -c%u /config)
if [ "$CURR_UID" != "$APP_UID" ] || [ "$CURR_GID" != "$APP_GID" ]; then
  chown -R $APP_UID:$APP_GID /config
fi
