FROM scratch
MAINTAINER hurricanehrndz@techbyte.ca

ADD Emby-Tumbleweed.tar.xz /
RUN zypper addrepo http://download.opensuse.org/repositories/home:hurricanehernandez/openSUSE_Tumbleweed/home:hurricanehernandez.repo
