FROM opensuse:leap
MAINTAINER HurricaneHrndz <carlos@techbyte.ca>

RUN zypper --non-interactive update \
 && zypper --non-interactive install libbz2-devel \
	libjasper-devel \
	liblcms2-devel \
	libtiff-devel \
	giflib-devel \
	zlib-devel \
	freetype-devel \
	libjpeg-devel \
	libpng-devel \
	libtool-ltdl-devel \
	libxml2-devel \
	fftw-devel \
	libwebp-devel \
	rpm-build
