#!/usr/bin/with-contenv bash
# vim:set ft=sh sw=2 sts=2 st=2 et:

EDGE=${EDGE:-0}

if [[ $EDGE -eq 1 ]]; then
  echo "Updating ${APP_NAME}..."
  zypper --quiet --non-interactive ref &> /dev/null
  zypper --quiet --non-interactive up --no-recommends ${PKG_NAME} &> /dev/null
  zypper cc --all &> /dev/null
  rm -rf /var/cache/zypp*
fi
